### ISSUE TITLE
Activating HelperPress WP Plugin

### ISSUE THREAD

**Issue by ckhicks** [40Digits/helperpress#48]
Just did a fresh HP install and got this when trying to active the WP plugin:

```
Plugin could not be activated because it triggered a fatal error.

Fatal error: Call to undefined function mcrypt_create_iv() in /Users/ckhicks/Git/qrs/custom_plugins/helperpress/Libs/API.php on line 33
```

**Comment by chuckmo** [comment]
PHP requires mcrypt to be installed and enabled. This has come up a few times, so I'm considering utilizing a different library to generate the API key.

**Comment by chuckmo** [comment]
Depending on how your PHP is setup, this may or may not be helpful:

http://coolestguidesontheplanet.com/install-mcrypt-php-mac-osx-10-10-yosemite-development-server/
